name: Cspell Lint                                            # Define the name of the workflow

on: [push, pull_request]                                     # Trigger the workflow on push and pull request events

jobs:                                                        # Initialise job
  lint:                                                      # Define a job named 'lint'
    runs-on: ubuntu-latest                                   # Specifies the type of VM to provision

    container:                                               # Set container image
      image: monkeyknuckles/cspell                           # Points to CSpell container

    steps:                                                   # List of steps to execute
      - name: Checkout code                                  # Checkout code label text
        uses: actions/checkout@v3                            # Use the checkout action to clone the repository

      - name: Copy CSpell config                             # Copy CSpell configuration file label text
        run: cp /app/cspell.config.yaml $GITHUB_WORKSPACE    # Include the CSpell configuration file in the docker build

      - name: Run Lint CSpell                                # Set lint CSpell label text
        run: cspell . --color --language-id en-GB            # Spellcheck all files
              
  
      