name: Stylelint Lint                                # Define the name of the workflow

on: [push, pull_request]                            # Trigger the workflow on push and pull request events

jobs:                                               # Initialise job
  lint:                                             # Define a job named 'lint'
    runs-on: ubuntu-latest                          # Specifies the type of VM to provision

    container:
      image: monkeyknuckles/stylelint               # Specifies the Docker container to use

    steps:
      - name: Checkout code                         # Set Checkout code label text
        uses: actions/checkout@v3                   # Set Github runner version

      - name: Run Stylelint                         # Set Stylelint label
        run: |                                      # Copy Stylelint config file then lint all CSS files 
             cp /app/.stylelintrc $GITHUB_WORKSPACE 
             stylelint .
                              